import { type NextPage } from "next";
import Head from "next/head";
import Chat from "~/components/Chat";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat-App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen   flex-col items-center justify-end gap-6 bg-gradient-to-b from-[#460d96]    to-[#15162c] lg:justify-center lg:gap-12">
        <h1 className="text-3xl  font-extrabold tracking-tight text-white sm:text-[5rem] lg:text-5xl">
          <span className="text-[hsl(280,100%,70%)]">Chat</span> App
        </h1>
        <div className=" h-[90vh] w-full md:h-5/6 md:min-h-[80vh]  xl:max-w-4xl 2xl:max-w-6xl">
          <Chat />
        </div>
      </main>
    </>
  );
};

export default Home;


